### ISSUE TITLE
[Recurso]: YesWeTrans

### ISSUE THREAD

**Issue by Alma-seich** [trans-en-espanol/transespdiscord-recursos#4]
### ¿Para cúal país es?

España

### ¿En que área aplica el recurso?

Nacional

### Información

Hay un programa de FELGTBI dedicado a la insercion sociolaboral de personas trans, se llama YesWeTrans, por si te parece interesante destacar el enlace.
Tengo experiencia con el proyecto y muy contenta.
https://felgtbi.org/yeswetrans/

**Comment by luciamb-dev** [comment]
Buenas, FELGTBI+ ya estaba, pero ahora además se ha destacado en la página de [contactos (España)](https://recursos.transespdiscord.net/#/paises/espana/contactos) que disponen de este programa. Muchas gracias.
